version: "4.1"
services:
  keycloak1:
    image: quay.io/keycloak/keycloak:18.0.2
    container_name: keycloak
    hostname: keycloak
    command:
      - "start-dev"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8880:8080"

  rabbit:
    image: rabbitmq
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
